#!/bin/bash -f
\rm -rf obj/ts/ethmac_zap
mkdir -p obj/ts/ethmac_zap/

#DEBUG_FLAGS="-DDEBUG -DDEBUG2"
DEBUG_FLAGS=""

arm-none-eabi-as -march=armv5te -g src/ts/ethmac_zap/uart.s -o obj/ts/ethmac_zap/uart_start.o
arm-none-eabi-gcc -c -msoft-float -mfloat-abi=soft -march=armv5te -ffreestanding -g -O2 -Isrc/ts/ethmac_zap $DEBUG_FLAGS src/ts/ethmac_zap/ethmac_zap.c -o obj/ts/ethmac_zap/ethmac_zap.o
arm-none-eabi-gcc -c -msoft-float -mfloat-abi=soft -march=armv5te -g src/ts/ethmac_zap/mini_libc.c -o obj/ts/ethmac_zap/mini_libc.o
arm-none-eabi-gcc -c -msoft-float -mfloat-abi=soft -march=armv5te -ffreestanding -g -O2 -Isrc/ts/ethmac_zap $DEBUG_FLAGS src/ts/ethmac_zap/ethmac_demo.c -o obj/ts/ethmac_zap/ethmac_demo.o
arm-none-eabi-gcc -c -msoft-float -mfloat-abi=soft -march=armv5te -ffreestanding -g -O2 -Isrc/ts/ethmac_zap $DEBUG_FLAGS src/ts/ethmac_zap/net_minip.c -o obj/ts/ethmac_zap/net_minip.o
arm-none-eabi-gcc -c -msoft-float -mfloat-abi=soft -march=armv5te -ffreestanding -g -O2 -Isrc/ts/ethmac_zap $DEBUG_FLAGS src/ts/ethmac_zap/ethmac_irq.c -o obj/ts/ethmac_zap/ethmac_irq.o
arm-none-eabi-gcc -c -msoft-float -mfloat-abi=soft -march=armv5te -ffreestanding -g -Isrc/ts/ethmac_zap $DEBUG_FLAGS src/ts/ethmac_zap/uart.c -o obj/ts/ethmac_zap/uart.o
arm-none-eabi-ld -T src/ts/common.ld obj/ts/ethmac_zap/uart_start.o \
                                     obj/ts/ethmac_zap/ethmac_zap.o \
                                     obj/ts/ethmac_zap/ethmac_demo.o \
                                     obj/ts/ethmac_zap/net_minip.o \
                                     obj/ts/ethmac_zap/ethmac_irq.o \
                                     obj/ts/ethmac_zap/mini_libc.o \
                                     obj/ts/ethmac_zap/uart.o \
                                     -o obj/ts/ethmac_zap/ethmac_zap.elf
arm-none-eabi-objcopy -O binary obj/ts/ethmac_zap/ethmac_zap.elf obj/ts/ethmac_zap/ethmac_zap.bin
hexdump -ve '1/4 "%08x\n"' obj/ts/ethmac_zap/ethmac_zap.bin > obj/ts/ethmac_zap/ethmac_zap.dump
arm-none-eabi-objdump -d obj/ts/ethmac_zap/ethmac_zap.elf > obj/ts/ethmac_zap/ethmac_zap_obj.dump
